## Understanding some advanced tensor operations in PyTorch

- torch.nn.functional.Pad
- torch.gather
- 
- 

In [2]:
import torch 
from torch import nn


#### Torch.nn.functional.pad

## Padding
    - `torch.nn.functional.pad(input, pad, mode='constant', value=0)`
      - input (Tensor) – N-dimensional tensor
      - pad (tuple) - (#_Padded left, #_padded right) * dim
      - mode (str) – ‘constant’, ‘reflect’, ‘replicate’ or ‘circular’. Default: ‘constant’  
        - value (float) – fill value for ‘constant’ padding. Default: 0
          - can be assigned with a value of tensor
for padding to work 

In [3]:
import torch.nn.functional as F
torch.manual_seed(0)

#* create 4D tensor
tensor_2d = torch.zeros(3, 4)
padding_val_1d= (1,1) #* (left, right) * (# of dim)

len(padding_val_1d)
values = [i for i in range(len(padding_val_1d)*tensor_2d.shape[0])]
#* for padding to work

print(tensor_2d.shape)
print(padding_val_1d)

#* padding

#* padding 1D tensor
padded_tensor = F.pad(tensor_2d, padding_val_1d, mode='constant', value=1.0)
print(padded_tensor.shape)

print(tensor_2d)
print(padded_tensor)

torch.Size([3, 4])
(1, 1)
torch.Size([3, 6])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 1.]])


## Cumulative prod 
    Tensor.cumprod(dim, dtype=None) → Tensor

In [5]:
tensor_1d = torch.tensor([1,2,3,4,5])
torch.cumprod(tensor_1d, dim=0)


tensor([  1,   2,   6,  24, 120])